export const LANDING_STEPS = [
  {
    number: '01',
    title: 'Generate a business idea worth chasing',
    desc: 'Combine proven actions, real workflows, and target industries to uncover concrete startup concepts, not vague inspiration.',
  },
  {
    number: '02',
    title: 'Know if it\'s worth building before you commit',
    desc: 'Every idea gets a free market check with competitor analysis, market size, and demand signals, then a clear build, caution, or avoid verdict.',
  },
  {
    number: '03',
    title: 'Turn the winner into a build-ready plan',
    desc: 'Unlock a full blueprint with product design, launch strategy, infrastructure, and prototype guidance across four AI specialists.',
  },
];

export const LANDING_TESTIMONIALS = [
  {
    name: 'Sarah K.',
    role: 'Founder, SaaS',
    text: 'I spun 12 ideas in 20 minutes. The market check killed 9 of them before I wasted a single hour. That\'s the point.',
  },
  {
    name: 'Marcus L.',
    role: 'Operator',
    text: 'The infrastructure breakdown alone saved me 3 hours of research. Every service I needed, with setup steps and cost estimates.',
  },
  {
    name: 'Priya M.',
    role: 'Product Manager',
    text: 'I was skeptical about AI ideation tools. This one validates before it builds. That\'s the difference. The avoid verdict on my first idea was genuinely useful.',
  },
];

export const FAQS = [
  {
    q: 'What is IdeaReels?',
    a: 'IdeaReels is an AI-powered startup ideation tool. Spin three reels to land on a business concept, get a free market validation, then unlock a full blueprint: product design, go-to-market plan, infrastructure, and a clickable prototype.',
  },
  {
    q: 'How do credits work?',
    a: 'Validation is free. You only spend credits when you want deeper output. Deep market research costs 1 credit and the full 4-agent blueprint costs 2 credits. Every new account starts with 3 free credits.',
  },
  {
    q: 'What does the blueprint include?',
    a: 'The full blueprint includes product strategy, launch planning, infrastructure recommendations, and a clickable prototype so you can pressure-test the concept quickly.',
  },
  {
    q: 'Is the market validation really free?',
    a: 'Yes. You can spin ideas and run the initial market check as many times as you want without spending credits. Credits are only for the deeper research and blueprint layers.',
  },
  {
    q: 'What if the market check says avoid?',
    a: 'No credit is spent. The point is to kill weak ideas early, before you waste time or money building the wrong thing.',
  },
  {
    q: 'Do credits expire?',
    a: 'No. Credits stay on your account until you use them.',
  },
];

export const LEGAL_PRIVACY = [
  {
    title: '1. Information we collect',
    body: 'When you create an account, we collect your email address and, if you sign in via OAuth, your name and profile picture from GitHub or Google. We also collect usage data such as spin history, validation requests, and blueprint generations to improve the product. Payment information is handled entirely by Stripe, we never store card numbers.',
  },
  {
    title: '2. How we use your information',
    body: 'We use your email to authenticate your account and send transactional emails. We use usage data to improve AI outputs and detect abuse. We do not sell your personal data to third parties.',
  },
  {
    title: '3. Cookies',
    body: 'We use cookies to keep you signed in via Supabase Auth and to remember your preferences. Declining non-essential cookies may prevent you from staying signed in.',
  },
  {
    title: '4. Third-party services',
    body: 'We use Supabase for database and authentication, Stripe for payments, Anthropic for AI generation, and Render for hosting. Each service has its own privacy policy.',
  },
  {
    title: '5. Data retention',
    body: 'We retain your account data for as long as your account is active. You can request deletion by emailing support@ideareels.io. Credits are non-transferable and are forfeited upon account deletion.',
  },
  {
    title: '6. Security',
    body: 'All data is transmitted over HTTPS. Passwords are never stored, we use magic links and OAuth only. Database access is controlled via row-level security policies.',
  },
  {
    title: '7. Contact',
    body: 'For privacy questions or data deletion requests, contact support@ideareels.io.',
  },
];

export const LEGAL_TERMS = [
  {
    title: '1. Acceptance',
    body: 'By using IdeaReels, you agree to these terms. If you do not agree, do not use the service.',
  },
  {
    title: '2. Service description',
    body: 'IdeaReels provides AI-powered startup idea generation, market validation, and blueprint creation. All outputs are generated by AI and are provided for informational and research purposes only.',
  },
  {
    title: '3. Credits and payments',
    body: 'Credits are purchased via Stripe and are non-refundable except in cases of technical failure. Credits never expire and are tied to your account. Pricing may change with notice.',
  },
  {
    title: '4. Acceptable use',
    body: 'You may not use IdeaReels to generate content that is illegal, harmful, or violates third-party rights. You may not attempt to reverse engineer, scrape, or abuse the service.',
  },
  {
    title: '5. AI-generated content',
    body: 'Market analysis, competitor data, financial projections, and all other AI-generated content may be inaccurate, incomplete, or outdated. You are responsible for decisions made based on this content.',
  },
  {
    title: '6. Intellectual property',
    body: 'You own the ideas and outputs you generate using IdeaReels. We do not claim ownership over your blueprints. By using the service, you grant us a limited license to process your inputs to generate outputs.',
  },
  {
    title: '7. Limitation of liability',
    body: 'IdeaReels is provided as is. We are not liable for indirect, incidental, or consequential damages arising from your use of the service.',
  },
  {
    title: '8. Contact',
    body: 'For questions about these terms, contact support@ideareels.io.',
  },
];
