import ZubazShell from '@/components/zubaz/ZubazShell';

export const metadata = {
  title: 'Terms of Service',
  description: 'Terms governing your use of IdeaReels.',
};

export default function TermsPage() {
  return (
    <ZubazShell>
      <section className="section zubuz-section-padding3">
        <div className="container">
          <div className="row justify-content-center">
            <div className="col-lg-8">
        <h1 style={s.h1}>Terms of Service</h1>
        <p style={s.meta}>Last updated: June 2026</p>

        {[
          {
            title: "1. Acceptance",
            body: "By using IdeaReels (ideareels.io), you agree to these terms. If you do not agree, do not use the service.",
          },
          {
            title: "2. Service description",
            body: "IdeaReels provides AI-powered startup idea generation, market validation, and blueprint creation. All outputs are generated by AI and are provided for informational and research purposes only. They do not constitute professional business, legal, financial, or investment advice.",
          },
          {
            title: "3. Credits and payments",
            body: "Credits are purchased via Stripe and are non-refundable except in cases of technical failure. Credits never expire and are tied to your account. Pricing may change with notice. Credits have no cash value and cannot be transferred or sold.",
          },
          {
            title: "4. Acceptable use",
            body: "You may not use IdeaReels to generate content that is illegal, harmful, or violates third-party rights. You may not attempt to reverse engineer, scrape, or abuse the service. We reserve the right to suspend accounts that violate these terms.",
          },
          {
            title: "5. AI-generated content",
            body: "Market analysis, competitor data, financial projections, and all other AI-generated content may be inaccurate, incomplete, or outdated. IdeaReels makes no warranties about the accuracy or completeness of AI outputs. You are solely responsible for any decisions made based on this content.",
          },
          {
            title: "6. Intellectual property",
            body: "You own the ideas and outputs you generate using IdeaReels. We do not claim ownership over your blueprints. By using the service, you grant us a limited license to process your inputs to generate outputs.",
          },
          {
            title: "7. Limitation of liability",
            body: "IdeaReels is provided 'as is'. We are not liable for any indirect, incidental, or consequential damages arising from your use of the service, including business losses based on AI-generated recommendations.",
          },
          {
            title: "8. Contact",
            body: "For questions about these terms, contact support@ideareels.io.",
          },
        ].map((section, i) => (
          <div key={i} style={s.section}>
            <h2 style={s.h2}>{section.title}</h2>
            <p style={s.body}>{section.body}</p>
          </div>
        ))}

            </div>
          </div>
        </div>
      </section>
    </ZubazShell>
  );
}

const s = {
  h1: { fontFamily: 'var(--font-display)', fontSize: 'clamp(28px,5vw,42px)', fontWeight: 700, letterSpacing: '-0.03em', margin: '0 0 8px', color: '#18112b' },
  meta: { fontSize: 13, color: '#aaa1bd', margin: '0 0 40px' },
  section: { marginBottom: 20, paddingBottom: 20, borderBottom: '1px solid #ece6f5' },
  h2: { fontFamily: 'var(--font-display)', fontSize: 18, fontWeight: 700, margin: '0 0 10px', color: '#18112b' },
  body: { fontSize: 14, color: '#463a5f', lineHeight: 1.8, margin: 0 },
};
