#!/usr/bin/env node
// Bundles PropFinder CSV exports into lib/nhl-data/seed/propfinder-<season>.js so
// the site shows season stats before anything has been imported into storage.
//   node tools/propfinder-seed.mjs <season> <csv> [<csv> ...]
// e.g. node tools/propfinder-seed.mjs 2025 ~/Downloads/nhl-skater-stats-*.csv ~/Downloads/nhl-team-stats-*.csv
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { basename, dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const [season, ...paths] = process.argv.slice(2);
if (!/^20\d{2}$/.test(season || '') || !paths.length) {
  console.error('usage: node tools/propfinder-seed.mjs <season> <csv> [<csv> ...]');
  process.exit(1);
}
const files = paths.map((p) => ({ name: basename(p), text: readFileSync(p, 'utf8').replace(/^﻿/, '').replace(/\r/g, '') }));
const esc = (s) => s.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$\{/g, '\\${');
const body = files.map((f) => `    { name: ${JSON.stringify(f.name)}, text: \`${esc(f.text)}\` },`).join('\n');
const out = `// Generated by tools/propfinder-seed.mjs — PropFinder CSV exports bundled with the
// site so lib/nhl-data/propfinder.js has season stats before any import. Do not edit.
export const PROPFINDER_SEED = {
  season: ${Number(season)},
  generatedAt: ${JSON.stringify(new Date().toISOString())},
  files: [
${body}
  ],
};
`;
const dir = join(dirname(fileURLToPath(import.meta.url)), '..', 'lib', 'nhl-data', 'seed');
mkdirSync(dir, { recursive: true });
const target = join(dir, `propfinder-${season}.js`);
writeFileSync(target, out);
console.log(`wrote ${target}: ${files.map((f) => `${f.name} (${f.text.split('\n').filter(Boolean).length} lines)`).join(', ')}`);
